export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "demo@devstash.io",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippets", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "Prompts", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "Commands", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "Notes", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_file", name: "Files", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Images", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "Links", icon: "Link", color: "#10b981", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    defaultTypeId: "type_snippet",
    itemCount: 12,
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    itemCount: 8,
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    defaultTypeId: "type_file",
    itemCount: 5,
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    defaultTypeId: "type_note",
    itemCount: 24,
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    defaultTypeId: "type_command",
    itemCount: 15,
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    defaultTypeId: "type_prompt",
    itemCount: 18,
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "TEXT" as const,
    content: "Custom authentication hook for React applications",
    description: "Custom authentication hook for React applications",
    language: "typescript",
    itemTypeId: "type_snippet",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    lastUsedAt: "2026-01-15T00:00:00Z",
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "TEXT" as const,
    content: "Fetch wrapper with exponential backoff retry logic",
    description: "Fetch wrapper with exponential backoff retry logic",
    language: "typescript",
    itemTypeId: "type_snippet",
    isFavorite: false,
    isPinned: true,
    tags: ["api", "error-handling"],
    lastUsedAt: "2026-01-12T00:00:00Z",
    createdAt: "2026-01-12T00:00:00Z",
  },
  {
    id: "item_3",
    title: "Git stash with message",
    contentType: "TEXT" as const,
    content: "git stash push -m 'my stash message'",
    description: null,
    language: null,
    itemTypeId: "type_command",
    isFavorite: false,
    isPinned: false,
    tags: ["git"],
    lastUsedAt: "2026-01-10T00:00:00Z",
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "item_4",
    title: "Python list comprehension",
    contentType: "TEXT" as const,
    content: "[x for x in range(10) if x % 2 == 0]",
    description: null,
    language: "python",
    itemTypeId: "type_snippet",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "list"],
    lastUsedAt: "2026-01-08T00:00:00Z",
    createdAt: "2026-01-08T00:00:00Z",
  },
  {
    id: "item_5",
    title: "Act as a senior code reviewer",
    contentType: "TEXT" as const,
    content: "You are a senior engineer. Review the following code for bugs, performance, and security issues.",
    description: null,
    language: null,
    itemTypeId: "type_prompt",
    isFavorite: true,
    isPinned: false,
    tags: ["code-review", "ai"],
    lastUsedAt: "2026-01-05T00:00:00Z",
    createdAt: "2026-01-05T00:00:00Z",
  },
];

export const mockItemTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_link: 8,
};
